name: Maven Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 9, 11, 13 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK for java ${{matrix.java}}
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java}}
      - name: Test with Maven, Java ${{matrix.java}}
        run: mvn -B package --file pom.xml -P dist
